# Default values for nae.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: nae

eclipseMosquitto:
  name: eclipse-mosquitto
  image: 
    repository: eclipse-mosquitto
    version: latest
  mqttPort: 1883
  mqttServicePort: 8560
  webSocketPort: 9000
  webSocketServicePort: 8561

mongoExpress:
  name: mongo-express
  image:
    repository: mongo-express
    version: latest
  # Port which exposes mongo-express on host
  # needs to be in range [30000,32767]
  nodePort: 30001

u10:
  name: u10
  image:
    repository: u10
    version: latest
  # Port which exposes u10 on host
  # needs to be in range [30000,32767]
  nodePort: 30000
