apiVersion: v1
kind: ConfigMap
metadata:
  name: a10-conf
  namespace: {{ .Values.namespace }}
data:
  a10.conf: |
    [Identification]
    asvrname = A10_local

    [Debugging]
    debug=on

    [Logging]
    logfile = /tmp/a10.log

    [mqtt]
    mqttclientname= a10mqtt
    mqttaddress=messagebus.nae
    mqttport=8560
    keepaliveping=15

    [mongo]
    mongodburl=mongodb://mongo.nae:27017/
    mongodbname=asvrlocal
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-conf
  namespace: {{ .Values.namespace }}
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true