kind: PersistentVolume
apiVersion: v1
metadata:
 name: mongo-pv
 labels:
  type: local
spec:
 storageClassName: manual
 capacity:
  storage: {{ .Values.mongo.volume.size }}
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: {{ .Values.mongo.volume.hostPath }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: mongo-pv-claim
 namespace: {{ .Values.namespace }}
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: {{ .Values.mongo.volume.size }}
